# Generated by Django 5.2.1 on 2025-05-13 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistclientrelationship',
            name='client',
            field=models.ForeignKey(limit_choices_to={'user_role': 'client'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='therapistclientrelationship',
            options={'verbose_name': 'Therapist-Client Relationship', 'verbose_name_plural': 'Therapist-Client Relationships'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Indicates if the user has completed their profile', verbose_name='Profile Completed'),
        ),
        migrations.AddField(
            model_name='user',
            name='survey_done',
            field=models.BooleanField(default=False, help_text='Indicates if the user has completed the initial survey', verbose_name='Survey Completed'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('client', 'Client'), ('therapist', 'Psychotherapist')], default='client', help_text='User role in the system', max_length=10, verbose_name='User Role'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
