# Generated by Django 5.2.1 on 2025-05-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_therapistclientrelationship_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='survey_done',
            field=models.BooleanField(default=False, help_text='Whether the user has completed the matching survey', verbose_name='Survey Completed'),
        ),
    ]
