# Generated by Django 5.2.1 on 2025-05-14 19:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the criterion (e.g., "Experience with anxiety")', max_length=255, verbose_name='Criterion Name')),
                ('description', models.TextField(help_text='Detailed description of what this criterion means', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Criterion',
                'verbose_name_plural': 'Criteria',
            },
        ),
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='Score from 1 to 9', validators=[django.core.validators.MinValueValidator(1, 'Score must be at least 1'), django.core.validators.MaxValueValidator(9, 'Score cannot be more than 9')], verbose_name='Score')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='matching.criterion', verbose_name='Criterion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Criterion Score',
                'verbose_name_plural': 'Criterion Scores',
                'unique_together': {('user', 'criterion')},
            },
        ),
    ]
