# Generated by Django 5.2.1 on 2025-05-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='score_meaning_1',
            field=models.TextField(blank=True, help_text='What does a score of 1 mean for this criterion? (e.g., "flexible, unstructured approach")', null=True, verbose_name='Score 1 Meaning'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='score_meaning_9',
            field=models.TextField(blank=True, help_text='What does a score of 9 mean for this criterion? (e.g., "very structured, with a plan and tasks")', null=True, verbose_name='Score 9 Meaning'),
        ),
    ]
