# Generated by Django 5.2.1 on 2025-05-13 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psychotherapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(help_text='Tell potential clients about yourself, your approach, and experience', verbose_name='About me')),
                ('education_institution', models.CharField(help_text='Name of your main educational institution', max_length=255, verbose_name='Educational Institution')),
                ('education_start_year', models.PositiveIntegerField(help_text='Year when your education started (1900-2100)', validators=[django.core.validators.MinValueValidator(1900, message='Year must be between 1900 and 2100'), django.core.validators.MaxValueValidator(2100, message='Year must be between 1900 and 2100')], verbose_name='Education Start Year')),
                ('education_end_year', models.PositiveIntegerField(blank=True, help_text='Year when your education ended (1900-2100)', null=True, validators=[django.core.validators.MinValueValidator(1900, message='Year must be between 1900 and 2100'), django.core.validators.MaxValueValidator(2100, message='Year must be between 1900 and 2100')], verbose_name='Education End Year')),
                ('experience', models.DecimalField(decimal_places=0, help_text='Years of professional experience', max_digits=3, verbose_name='Years of Experience')),
                ('price', models.DecimalField(decimal_places=0, help_text='Price per session in your local currency', max_digits=10, verbose_name='Session Price')),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates if the therapist has been verified by the platform', verbose_name='Verified Professional')),
            ],
            options={
                'verbose_name': 'Psychotherapist',
                'verbose_name_plural': 'Psychotherapists',
            },
        ),
        migrations.CreateModel(
            name='WorkingMethodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Working Methodology',
                'verbose_name_plural': 'Working Methodologies',
            },
        ),
    ]
