# Generated by Django 5.2.1 on 2025-05-13 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('psychotherapists', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychotherapist',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='therapist', to='users.user'),
        ),
        migrations.AddField(
            model_name='psychotherapist',
            name='working_methodology',
            field=models.ForeignKey(help_text='Select your main therapeutic approach', on_delete=django.db.models.deletion.PROTECT, to='psychotherapists.workingmethodology', verbose_name='Primary Working Methodology'),
        ),
    ]
