# Generated by Django 5.2.1 on 2025-05-13 17:13

import django.core.validators
import psychotherapists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapists', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychotherapist',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='psychotherapist',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, help_text='Select your gender', max_length=1, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psychotherapist',
            name='image',
            field=models.ImageField(default='static/img/profile.png', help_text='Upload your profile photo', upload_to='therapist_photos/', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='psychotherapist',
            name='education_end_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year when your education ended (optional)', null=True, validators=[django.core.validators.MinValueValidator(1900, message='Education end year must be between 1900 and current year'), django.core.validators.MaxValueValidator(psychotherapists.models.get_current_year, message='Education end year cannot be in the future')], verbose_name='Education End Year'),
        ),
        migrations.AlterField(
            model_name='psychotherapist',
            name='education_start_year',
            field=models.PositiveIntegerField(help_text='Year when your education started', validators=[django.core.validators.MinValueValidator(1900, message='Education start year must be between 1900 and current year'), django.core.validators.MaxValueValidator(psychotherapists.models.get_current_year, message='Education start year cannot be in the future')], verbose_name='Education Start Year'),
        ),
        migrations.AlterField(
            model_name='psychotherapist',
            name='experience',
            field=models.PositiveIntegerField(help_text='Years of professional experience', validators=[django.core.validators.MinValueValidator(0, message='Experience years cannot be negative'), django.core.validators.MaxValueValidator(100, message='Experience years seems too high')], verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='psychotherapist',
            name='price',
            field=models.PositiveIntegerField(help_text='Price per session in your local currency', validators=[django.core.validators.MinValueValidator(1, message='Price must be greater than 0'), django.core.validators.MaxValueValidator(10000, message='Price seems too high')], verbose_name='Session Price'),
        ),
    ]
