# Generated by Django 5.2.1 on 2025-05-13 18:20

import django.core.validators
import django.db.models.deletion
import psychotherapists.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapists', '0003_remove_psychotherapist_is_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='psychotherapist',
            name='birth_date',
            field=models.DateField(default=None, help_text='Your date of birth', validators=[django.core.validators.MinValueValidator(psychotherapists.models.get_min_birth_date, message='You must be at least 25 years old to register as a therapist'), django.core.validators.MaxValueValidator(psychotherapists.models.get_max_birth_date, message='Invalid birth date')], verbose_name='Birth Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='psychotherapist',
            name='education_end_year',
            field=models.PositiveIntegerField(help_text='Year when your education ended', validators=[django.core.validators.MinValueValidator(1940, message='Education end year must be between 1940 and current year'), django.core.validators.MaxValueValidator(psychotherapists.models.get_current_year, message='Education end year cannot be in the future')], verbose_name='Education End Year'),
        ),
        migrations.AlterField(
            model_name='psychotherapist',
            name='education_start_year',
            field=models.PositiveIntegerField(help_text='Year when your education started', validators=[django.core.validators.MinValueValidator(1940, message='Education start year must be between 1940 and current year'), django.core.validators.MaxValueValidator(psychotherapists.models.get_current_year, message='Education start year cannot be in the future')], verbose_name='Education Start Year'),
        ),
        migrations.AlterField(
            model_name='psychotherapist',
            name='image',
            field=models.ImageField(blank=True, default='static/img/profile.png', help_text='Upload your profile photo (optional)', null=True, upload_to='therapist_photos/', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='psychotherapist',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_role': 'therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='therapist', to=settings.AUTH_USER_MODEL),
        ),
    ]
