# Generated by Django 5.2.1 on 2025-05-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapists', '0004_psychotherapist_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psychotherapist',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'Psychotherapist', 'verbose_name_plural': 'Psychotherapists'},
        ),
        migrations.AlterField(
            model_name='psychotherapist',
            name='birth_date',
            field=models.DateField(help_text='Your date of birth (you must be at least 25 years old)', verbose_name='Birth Date'),
        ),
    ]
