# Generated by Django 5.2.1 on 2025-05-14 14:51

import django.core.validators
import psychotherapists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapists', '0005_alter_psychotherapist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychotherapist',
            name='image',
            field=models.ImageField(blank=True, default='static/img/profile.png', help_text='Upload your profile photo (JPEG or PNG only)', null=True, upload_to='therapist_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), psychotherapists.models.validate_image_file], verbose_name='Profile Photo'),
        ),
    ]
